version: "3.9"
services:
  app:
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env-dev
  caddy:
    image: caddy:2.3.0
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    environment:
        SITE_ADDRESS: ${SITE_ADDRESS:-localhost:80}
        APP_ADDRESS: ${APP_ADDRESS:-app:5000}
    depends_on:
      - app
