version: "3.9"
services:
  app:
    container_name: app
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env-dev
  caddy:
    image: caddy:2.3.0
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "caddy-data:/data/caddy"
      - "caddy-config:/config/caddy"
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-8081}:443
    env_file:
      - .env-dev
    depends_on:
      - app
volumes:
  caddy-data:
  caddy-config:
